# Generated by Django 2.1 on 2018-08-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apptest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='TITLE')),
                ('Content', models.TextField(verbose_name='CONTENT')),
            ],
        ),
    ]
